/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_ufmg_patentes.Interfaces;

import com.mycompany.projeto_ufmg_patentes.Classes.Autor;
import com.mycompany.projeto_ufmg_patentes.Classes.ModeloTabela;
import com.mycompany.projeto_ufmg_patentes.Classes.Patente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.mail.DefaultAuthenticator;
import org.apache.commons.mail.SimpleEmail;
import java.awt.Color;
import javax.swing.JScrollPane;
import javax.swing.UIDefaults;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author mylle
 */
public class TelaPatentes extends javax.swing.JFrame {

    /**
     * Creates new form TelaPatentes
     */
    public TelaPatentes() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPatentes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaAutores = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelAlertaEmail = new javax.swing.JLabel();
        labelNomeAutor = new javax.swing.JLabel();
        labelTelefoneAutor = new javax.swing.JLabel();
        labelEmailAutor = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEviarEmail1 = new javax.swing.JButton();
        btnMenuEmailEnviados = new javax.swing.JButton();
        btnMenuEditar1 = new javax.swing.JButton();
        btnMenuFiltroAno = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("Selecione uma categoria:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Bem vindo a área de Patentes");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("Selecione uma patente:");

        jComboBoxCategoria.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxCategoria.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBoxCategoria.setForeground(new java.awt.Color(255, 255, 204));
        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção", "Ciências Biológicas", "Ciências Exatas", "Engenharia", "Farmácia" }));
        jComboBoxCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCategoriaItemStateChanged(evt);
            }
        });

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 204));

        tabelaPatentes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tabelaPatentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número Pedido", "Titulo", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPatentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelaPatentesMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPatentes);

        tabelaAutores.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tabelaAutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Autores"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaAutores.setToolTipText("");
        tabelaAutores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelaAutoresMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaAutores);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do autor selecionado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 255, 204))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 204));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("Nome:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("Telefone:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setText("Email:");

        labelAlertaEmail.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelAlertaEmail.setForeground(new java.awt.Color(255, 102, 102));
        labelAlertaEmail.setText("Obs: Já foi enviado email para este autor!");

        labelNomeAutor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelNomeAutor.setForeground(new java.awt.Color(255, 255, 204));
        labelNomeAutor.setText("nome");

        labelTelefoneAutor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelTelefoneAutor.setForeground(new java.awt.Color(255, 255, 204));
        labelTelefoneAutor.setText("telefone");

        labelEmailAutor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelEmailAutor.setForeground(new java.awt.Color(255, 255, 204));
        labelEmailAutor.setText("email");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNomeAutor))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTelefoneAutor))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelEmailAutor))
                    .addComponent(labelAlertaEmail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelNomeAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelTelefoneAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelEmailAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAlertaEmail)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("Selecione um autor:");

        btnEviarEmail1.setBackground(new java.awt.Color(51, 51, 51));
        btnEviarEmail1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEviarEmail1.setForeground(new java.awt.Color(255, 255, 204));
        btnEviarEmail1.setText("Enviar email");
        btnEviarEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEviarEmail1ActionPerformed(evt);
            }
        });

        btnMenuEmailEnviados.setBackground(new java.awt.Color(255, 255, 204));
        btnMenuEmailEnviados.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMenuEmailEnviados.setForeground(new java.awt.Color(51, 51, 51));
        btnMenuEmailEnviados.setText("Emails Enviados");
        btnMenuEmailEnviados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuEmailEnviadosActionPerformed(evt);
            }
        });

        btnMenuEditar1.setBackground(new java.awt.Color(255, 255, 204));
        btnMenuEditar1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMenuEditar1.setForeground(new java.awt.Color(51, 51, 51));
        btnMenuEditar1.setText("Editar Autor");
        btnMenuEditar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuEditar1ActionPerformed(evt);
            }
        });

        btnMenuFiltroAno.setBackground(new java.awt.Color(255, 255, 204));
        btnMenuFiltroAno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMenuFiltroAno.setForeground(new java.awt.Color(51, 51, 51));
        btnMenuFiltroAno.setText("Filtro por Ano");
        btnMenuFiltroAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuFiltroAnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEviarEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(122, 122, 122))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnMenuEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnMenuEmailEnviados, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnMenuFiltroAno, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(27, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenuEmailEnviados, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuFiltroAno, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnEviarEmail1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaItemStateChanged
        // TODO add your handling code here:
        //((DefaultTableModel) tabelaAutores.getModel()).setRowCount(0);
        limparTabelaAutor();
        limparTabelaPatentes();
        desabilitarLabelAutores();
        if (jComboBoxCategoria.getSelectedIndex() != 0) {
            String categoria = jComboBoxCategoria.getSelectedItem().toString();
            Patente patente = new Patente();
            patente.preencherTabelaPatentes(tabelaPatentes, categoria);

        }

    }//GEN-LAST:event_jComboBoxCategoriaItemStateChanged

    private void tabelaPatentesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPatentesMouseReleased
        // TODO add your handling code here:
        int linhaSel = tabelaPatentes.getSelectedRow();
        if (linhaSel != -1) {
            String categoria = jComboBoxCategoria.getSelectedItem().toString();
            String num_pedido = tabelaPatentes.getValueAt(linhaSel, 0).toString();
            Patente patente = new Patente();
            patente.preencherTabelaAutores(tabelaAutores, categoria, num_pedido);

        }
    }//GEN-LAST:event_tabelaPatentesMouseReleased

    private void tabelaAutoresMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAutoresMouseReleased
        int linhaSel = tabelaAutores.getSelectedRow();
        if (linhaSel != -1) {

            String autorSel = tabelaAutores.getValueAt(linhaSel, 0).toString();
            Autor autor = new Autor();
            System.out.println("test? " + autor.getNome());
            autor.buscarDadosEspecAutores(autorSel);

            labelNomeAutor.setText(autor.getNome());
            labelTelefoneAutor.setText(autor.getCelular());
            labelEmailAutor.setText(autor.getEmail());

            habilitarLabelAutores();
            labelAlertaEmail.setVisible(false);
            if (autor.isEmail_enviado()) {
                labelAlertaEmail.setVisible(true);
            }
        }
    }//GEN-LAST:event_tabelaAutoresMouseReleased

    private void btnEviarEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEviarEmail1ActionPerformed

        String meuEmail = "carlosmiguel.dsa12@gmail.com";
        String senha = " ";

        SimpleEmail email = new SimpleEmail();
        email.setHostName("smtp.gmail.com");
        email.setSmtpPort(587);
        email.setAuthenticator(new DefaultAuthenticator(meuEmail, senha));

        email.setSSLOnConnect(true);
        String categoriaPatente = jComboBoxCategoria.getSelectedItem().toString();

        try {
            email.setFrom(meuEmail);
            email.setSubject("Fwd: Envio de Portifólio");
            email.setMsg("Compartilhando e-mail enviado para os professores da unidade de "+categoriaPatente+"\n"
                + "\n"
                + "Atenciosamente, \n"
                + "Carlos Miguel\n\n\n"
                + "Prezado (a) Professor (a),\n"
                + "\n"
                + "\n"
                + "\n"
                + "Sua participação é muito importante para conhecer um pouco mais sobre a experiência vivenciada com meus projetos e gostaria de ouvir opinião sobre meus projetos.\n"
                + "\n"
                + "Segue o link : \n"
                + "\n"
                + "https://karmiguel.github.io/Portifolio/portfolio.html"
                + "\n"
                + "Qualquer dúvida estou à disposição para esclarecê-la.\n"
                + "Agradeço antecipadamente a atenção e apoio.\n"
                + "\n"
                + "\n"
                + "Atenciosamente,\n"
                + "Carlo Miguel dos Santos Alves\n"
                + "\n"
                + "Aluno IFNMG/MG\n"
                + "\n"
                + "(38) 99966 - 1117\n");
            email.addTo(labelEmailAutor.getText());
            email.send();
            System.out.println("Email enviado com sucesso!");
            
            Autor autor =  new Autor();
            JOptionPane.showMessageDialog(rootPane, "Email enviado com sucesso!!!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
            
            autor.marcarEmailEnviado(labelNomeAutor.getText());

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Email inválido !", "Erro ao enviar email!!", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btnEviarEmail1ActionPerformed

    private void btnMenuEmailEnviadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuEmailEnviadosActionPerformed
        new TelaEmailEnviados().setVisible(true);
        dispose();

    }//GEN-LAST:event_btnMenuEmailEnviadosActionPerformed

    private void btnMenuEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuEditar1ActionPerformed

        int linhaSelecionada = tabelaAutores.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha na tabela de autor para atualizar.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String autorSel = tabelaAutores.getValueAt(linhaSelecionada, 0).toString();
        Autor autor = new Autor();
        autor.buscarDadosEspecAutores(autorSel);

        System.out.println("id autor =" + autor.getId());
        new TelaEditarAutor(autorSel).setVisible(true);
    }//GEN-LAST:event_btnMenuEditar1ActionPerformed

    private void btnMenuFiltroAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuFiltroAnoActionPerformed
        new TelaFiltroAno().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenuFiltroAnoActionPerformed

    public void limparTabelaPatentes() {
        String[] colunas = new String[]{"Número Pedido", "Título", "Data"};
        ArrayList dados = new ArrayList();
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        tabelaPatentes.setModel(modelo);
    }

    public void limparTabelaAutor() {
        String[] colunas = new String[]{"Autores"};
        ArrayList dados = new ArrayList();
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        tabelaAutores.setModel(modelo);
    }

    public void habilitarLabelAutores() {
        labelNomeAutor.setVisible(true);
        labelTelefoneAutor.setVisible(true);
        labelEmailAutor.setVisible(true);
    }

    public void desabilitarLabelAutores() {
        labelNomeAutor.setVisible(false);
        labelTelefoneAutor.setVisible(false);
        labelEmailAutor.setVisible(false);
        labelAlertaEmail.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPatentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPatentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPatentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPatentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPatentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEviarEmail1;
    private javax.swing.JButton btnMenuEditar1;
    private javax.swing.JButton btnMenuEmailEnviados;
    private javax.swing.JButton btnMenuFiltroAno;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelAlertaEmail;
    private javax.swing.JLabel labelEmailAutor;
    private javax.swing.JLabel labelNomeAutor;
    private javax.swing.JLabel labelTelefoneAutor;
    private javax.swing.JTable tabelaAutores;
    private javax.swing.JTable tabelaPatentes;
    // End of variables declaration//GEN-END:variables
}
